// <auto-generated />
using System;
using Cex.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cex.Infrastructure.Migrations
{
    [DbContext(typeof(CexDbContext))]
    [Migration("20251119185311_TradeHistory")]
    partial class TradeHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cex.Domain.Entities.BnbSetting", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("BnbSettings");
                });

            modelBuilder.Entity("Cex.Domain.Entities.SpotGrid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BaseBalance")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GridMode")
                        .HasColumnType("int");

                    b.Property<decimal>("Investment")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<decimal>("LowerPrice")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<int>("NumberOfGrids")
                        .HasColumnType("int");

                    b.Property<decimal>("Profit")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<decimal>("QuoteBalance")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<decimal>("TriggerPrice")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UpperPrice")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpotGrids");
                });

            modelBuilder.Entity("Cex.Domain.Entities.SpotGridStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BuyPrice")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Qty")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<decimal>("SellPrice")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<long>("SpotGridId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("SpotGridId");

                    b.ToTable("SpotGridSteps");
                });

            modelBuilder.Entity("Cex.Domain.Entities.SpotOrder", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("FeeCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWorking")
                        .HasColumnType("bit");

                    b.Property<decimal>("OrigQty")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Price")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<string>("Side")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SpotGridStepId")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeInForce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WorkingTime")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("SpotGridStepId");

                    b.ToTable("SpotOrders");
                });

            modelBuilder.Entity("Cex.Domain.Entities.SpotOrderSyncSetting", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "Symbol");

                    b.ToTable("SpotOrderSyncSettings");
                });

            modelBuilder.Entity("Cex.Domain.Entities.TradeHistory", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("TradeId")
                        .HasColumnType("bigint");

                    b.Property<string>("CounterOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 11, 19, 18, 53, 10, 803, DateTimeKind.Utc).AddTicks(5040));

                    b.Property<decimal>("Fee")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<string>("FeeCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FeeRate")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<bool>("ForceTaker")
                        .HasColumnType("bit");

                    b.Property<decimal>("Funds")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<string>("Liquidity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Size")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<string>("Stop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TradedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "TradeId");

                    b.ToTable("TradeHistories");
                });

            modelBuilder.Entity("Cex.Domain.Entities.SpotGridStep", b =>
                {
                    b.HasOne("Cex.Domain.Entities.SpotGrid", null)
                        .WithMany("GridSteps")
                        .HasForeignKey("SpotGridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cex.Domain.Entities.SpotOrder", b =>
                {
                    b.HasOne("Cex.Domain.Entities.SpotGridStep", null)
                        .WithMany("Orders")
                        .HasForeignKey("SpotGridStepId");
                });

            modelBuilder.Entity("Cex.Domain.Entities.SpotGrid", b =>
                {
                    b.Navigation("GridSteps");
                });

            modelBuilder.Entity("Cex.Domain.Entities.SpotGridStep", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
